apiVersion: v1
kind: Service
metadata:
  name: busqueda-profesionales-ms-service
spec:
  selector:
    app: busqueda-profesionales-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

